auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    # github:
    #   development:
    #     clientId: ${AUTH_GITHUB_CLIENT_ID}
    #     clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

# integrations:
#   github:
#     - host: github.com
#       apps:
#         - $include: github-app-credentials.yaml

app:
  title: RHDH
  baseUrl: ${BASE_URL}

backend:
  listen:
    port: 7007
  baseUrl: ${BASE_URL}
  # uncomment this if backend.baseUrl is exposed over HTTPS
  # and you want RHDH to auto-generate and serve a self-signed certificate.
  # https: true
  cors:
    origin: ${BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  csp:
    upgrade-insecure-requests: false
    img-src:
      # "'self'" and 'data' are from the backstage default but must be set since img-src is overwritten
      - "'self'"
      - "data:"
      - https://upload.wikimedia.org
      - https://podman-desktop.io
      - https://argo-cd.readthedocs.io
      - https://instructlab.ai
      - https://quay.io

  # comment out the following 'database' section to use the PostgreSQL database
  database:
    client: better-sqlite3
    connection: ":memory:"

  auth:
    keys:
      - secret: "development"

# You can use local files from catalog-entities directory to load entities into the catalog
catalog:
  rules:
    - allow: [Component, API, Location, Template, Domain, User, Group, System, Resource]

  locations:
    - type: file
      target: /opt/app-root/src/configs/catalog-entities/users.yaml
      rules:
        - allow: [User, Group]
    - type: file
      target: /opt/app-root/src/configs/catalog-entities/components.yaml
      rules:
        - allow: [Component, System]
    - type: url
      target: https://github.com/redhat-ai-dev/model-catalog-example/blob/v0.1/developer-model-service/catalog-info.yaml
      rules:
        - allow: [Component, Resource, Api]
    - type: url
      target: https://github.com/redhat-ai-dev/model-catalog-example/blob/v0.1/ollama-model-service/catalog-info.yaml
      rules:
        - allow: [Component, Resource, Api]
    - type: url
      target: https://github.com/redhat-ai-dev/ai-lab-template/blob/release-v0.9.x/all.yaml
      rules:
        - allow: [Template]

techdocs:
  generator:
    runIn: local
  builder: local
  publisher:
    type: local
    local:
      publishDirectory: /tmp/techdocs
